# Generated by Django 5.1.5 on 2025-01-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.CharField(
                choices=[
                    ("lifestyle", "ไลฟ์สไตล์"),
                    ("news", "ข่าวสาร"),
                    ("product recommendatons", "แนะนำสินค้า"),
                ],
                max_length=50,
            ),
        ),
    ]
