# Generated by Django 5.1.5 on 2025-02-19 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="date_of_birth",
            new_name="birthday",
        ),
    ]
