# Generated by Django 5.1.5 on 2025-01-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "ชาย"), ("female", "หญิง"), ("other", "อื่น ๆ")],
                max_length=10,
            ),
        ),
    ]
