# Generated by Django 5.1.5 on 2025-01-26 20:17

import django.db.models.deletion
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=orders.models.upload_to
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="shippingmethod",
            name="method_name",
            field=models.CharField(
                choices=[("car", "รถ"), ("boat", "เรือ")], max_length=50
            ),
        ),
    ]
