# Generated by Django 5.1.5 on 2025-02-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "รอการชำระเงิน"),
                    ("paid", "จ่ายแล้ว"),
                    ("completed", "สำเร็จ"),
                    ("cancelled", "ยกเลิก"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
